# Generated by Django 2.2.6 on 2019-10-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='open_data',
            new_name='open_date',
        ),
    ]
